o: Skip non existing args.

diff --git a/functions/o b/functions/o
--- a/functions/o
+++ b/functions/o
@@ -3,8 +3,16 @@
 #
 
 for arg; do
+  if [ ! -f "$arg" ]; then
+    echo "Error: $arg does not exist." >&2
+    continue
+  elif [ ! -r "$arg" ]; then
+    echo "Error: $arg is not readable." >&2
+    continue
+  fi
   case $(xdg-mime query filetype "$arg") in
-    text/*|inode/x-empty) gvim --remote-tab "$arg";;
+    text/html|text/htm) browser "$arg" &!;;
+    text/*|inode/x-empty) ${EDITOR:-vi} "$arg";;
     *) xdg-open "$arg" &!;;
   esac
 done
